name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: cd packages/ia-icons && npm install && npm dedupe

    - name: Run tests
      run: cd packages/ia-icons && npm run test

    - name: Upload reports
      run: npx codecov
